import './globals.css';
import { PT_Sans } from 'next/font/google'
import Navbar from '@/components/Shared/Navbar';


const sans = PT_Sans({ subsets: ['latin'], weight: ['400', '700'] });


export const metadata = {
  title: 'Walker App',
  description: 'Generated by rakibul hasan',
}

export default function RootLayout({ children }) {
  return (
    <html className={sans.className} lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
